[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dynvpn"
version = "0.1"
authors = [
]
description = ""
readme = ""
requires-python = ">=3.11"
dependencies=[
    "aiohttp",
    "pyyaml",
]
classifiers = [
]

